/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.Benito.ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.Benito.entidades.Articulo;
import mx.itson.Benito.entidades.OrdenCompra;
import mx.itson.Benito.entidades.Proveedor;
import mx.itson.Benito.persistencia.OrdenCompraDAO;

/**
 * se motrara los datos desde una tabla con sus dotones de agregar, editar y eliminar 
 * @author pyatq
 */
public class OrdenCompraListado extends javax.swing.JFrame {
    
    int id;
    String pedido;
    String direccion;
    String telefono;
    String personaCompra;
    String folio;
    String total;
    Articulo articulo;
    Proveedor proveedor;

    /**
     * Creates new form OrdenCompraListado
     */
    public OrdenCompraListado() {
        initComponents();
         this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrden = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Pedido", "Direccion", "Telefono", "Persona de Compra", "Folio", "Total", "Articulo", "Proveedor"
            }
        ));
        jScrollPane1.setViewportView(tblOrden);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(62, 62, 62)
                .addComponent(btnEditar)
                .addGap(64, 64, 64)
                .addComponent(btnEliminar)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        List<OrdenCompra> ordencompra = OrdenCompraDAO.obtenerTodos();
        DefaultTableModel modelo = (DefaultTableModel) tblOrden.getModel();
        modelo.setRowCount(0);

        for (OrdenCompra O : ordencompra) {
            modelo.addRow(new Object[]{
                O.getId(),
                O.getPedido(),
                O.getDireccion(),
                O.getTelefono(),
                O.getPersonaCompra(),
                O.getFolio(),
                O.getTotal(),
                O.getArticulo().getNombre(),
                O.getProveedor().getNombre()
            });
     }

    }//GEN-LAST:event_formWindowOpened

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        OrdenCompraFormulario formulario = new OrdenCompraFormulario(this, true, id, pedido, direccion, telefono, personaCompra, folio, total, articulo, proveedor);
        
        formulario.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblOrden.getModel();
        int fila = tblOrden.getSelectedRow();
        int id = Integer.parseInt(modelo.getValueAt(fila,0).toString());
        String pedido = modelo.getValueAt(fila, 1).toString();
        String direccion = modelo.getValueAt(fila, 2).toString();
        String telefono = modelo.getValueAt(fila, 3).toString();
        String personaCompra = modelo.getValueAt(fila, 4).toString();
        String folio = modelo.getValueAt(fila, 5).toString();
        String total = modelo.getValueAt(fila, 6).toString();

       OrdenCompraFormulario formulario = new OrdenCompraFormulario(this, true, id, pedido, direccion, telefono, personaCompra, folio, total, articulo, proveedor);
        
        formulario.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int O = JOptionPane.showConfirmDialog(this, "Estas seguro de eliminar los datos de Orden de Compra?","estas Seguro?", JOptionPane.YES_NO_OPTION);
                
        if(O == 0){
        DefaultTableModel modelo = (DefaultTableModel) tblOrden.getModel();
        
        int fila = tblOrden.getSelectedRow();
        int id = Integer.parseInt(modelo.getValueAt(fila,0).toString());
        
        boolean operacion = false;
        try{
            
        OrdenCompraDAO ordenDAO = new OrdenCompraDAO();
        operacion = ordenDAO.eliminar(id);
        
        }catch(Exception ex){
         System.err.println("Ocurrio un error: " + ex);
        }
        
        if(operacion == true){
        JOptionPane.showMessageDialog(this, "La operacion de eliminacion fue exitosa","Operacion excitosa", JOptionPane.INFORMATION_MESSAGE);
        
        }else{
        JOptionPane.showMessageDialog(this, "No se ha pudido eliminar","Operacion fallida", JOptionPane.WARNING_MESSAGE);
        
        }
        
        this.dispose();
           OrdenCompraListado frame = new OrdenCompraListado();
            frame.setVisible(true);
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenCompraListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenCompraListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenCompraListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenCompraListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenCompraListado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrden;
    // End of variables declaration//GEN-END:variables
}
