/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mx.itson.Benito.ui;

import static java.awt.image.ImageObserver.ERROR;
import java.util.List;
import javax.swing.JOptionPane;
import mx.itson.Benito.entidades.Articulo;
import mx.itson.Benito.entidades.Proveedor;
import mx.itson.Benito.persistencia.ArticuloDAO;
import mx.itson.Benito.persistencia.OrdenCompraDAO;
import mx.itson.Benito.persistencia.ProveedorDAO;

/**
 *
 * @author pyatq
 */
public class OrdenCompraFormulario extends javax.swing.JDialog {
    
    int id;
    String pedido;
    String direccion;
    String telefono;
    String personaCompra;
    String folio;
    String total;
    Articulo articulo;
    Proveedor proveedor;

    /**
     * Creates new form OrdenCompraFormulario
     */
    public OrdenCompraFormulario(java.awt.Frame parent, boolean modal, int id, String pedido, String direccion, String telefono, String personaCompra, String folio, String total, Articulo articulo, Proveedor proveedor) {
        super(parent, modal);
        initComponents();
        
        this.id = id;
        this.pedido = pedido;
        this.direccion = direccion;
        this.telefono = telefono;
        this.personaCompra = personaCompra;
        this.folio = folio;
        this.total = total;
        this.articulo = articulo;
        this.proveedor = proveedor;
        
        cargarFormulario();
        
        cargarProveedor();
        
        cargarArticulo();
        
        setLocationRelativeTo(null);
        
        
        txtPedido.setText(pedido);
        txtDireccion.setText(direccion);
        txtTelefono.setText(telefono);
        txtPersonaCompra.setText(personaCompra);
        txtFolio.setText(folio);
        txtTotal.setText(total);
        cmbArticulo.addItem(articulo);
        cmbProveedor.addItem(proveedor);
        
        
    }
    
      public void cargarFormulario(){
        if(this.id != 0){
        }
    }
    
       public void cargarArticulo(){
        List<Articulo> articulos = ArticuloDAO.obtenerTodos();
        for(Articulo a : articulos){
            cmbArticulo.addItem(a);
        }
    }
       
    public void cargarProveedor(){
        List<Proveedor> proveedores = ProveedorDAO.obtenerTodos();
        for(Proveedor p : proveedores){
            cmbProveedor.addItem(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPersonaCompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbArticulo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbProveedor = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pedido:");

        jLabel2.setText("Direccion:");

        jLabel3.setText("Telefono:");

        jLabel4.setText("Persona de Compra: ");

        jLabel5.setText("Folio:");

        jLabel6.setText("Total:");

        jLabel7.setText("Articulo:");

        jLabel8.setText("Proveedor:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPedido)
                            .addComponent(txtDireccion)
                            .addComponent(txtTelefono)
                            .addComponent(txtPersonaCompra)
                            .addComponent(txtFolio)
                            .addComponent(txtTotal)
                            .addComponent(cmbArticulo, 0, 337, Short.MAX_VALUE)
                            .addComponent(cmbProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPersonaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String pedido = txtPedido.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        String personaCompra = txtPersonaCompra.getText();
        String folio = txtFolio.getText();
        String total = txtTotal.getText();
        Articulo articulo = (Articulo)cmbArticulo.getSelectedItem();
        Proveedor proveedor = (Proveedor)cmbProveedor.getSelectedItem();
        
        boolean operacion = false;
        
        if(this.id == 0 ){
        operacion = OrdenCompraDAO.guardar(pedido, direccion, telefono, personaCompra, folio, WIDTH, articulo, proveedor);
        }else{
            
        OrdenCompraDAO Orden = new OrdenCompraDAO();
        operacion = Orden.editar(id, pedido, direccion, telefono, personaCompra, folio, WIDTH, articulo, proveedor);
        }
        
        
        if(operacion == true){
        JOptionPane.showMessageDialog(this, "Se a Guardado exitasamente","Operacion excitosa", JOptionPane.INFORMATION_MESSAGE);
        
        }else{
        JOptionPane.showMessageDialog(this, "No se a podido guardar","Operacion fallida", JOptionPane.WARNING_MESSAGE);
        }
        
        this.dispose();
        OrdenCompraListado frame = new OrdenCompraListado();
        frame.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Articulo> cmbArticulo;
    private javax.swing.JComboBox<Proveedor> cmbProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtPedido;
    private javax.swing.JTextField txtPersonaCompra;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
